apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: k8
    subset: devops
  annotations:
    kubernetes.io/created-by: 'kubernetes'
spec:
  containers:
  - name: nginx
    image: nginx

