apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:
    name: frontend
    project: expense
    component: frontned
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80